name: First Workflow
on:
  schedule:
    - cron: '0 0 1 */3 *'
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
    
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hey"

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: List files in repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree

      - run: echo '### Hello world! :rocket:' >> $GITHUB_STEP_SUMMARY
